openapi: 3.0.0
info:
  title: Customer API
  version: 1.0.0
paths:
  /customers/{customerId}:
    put:
      summary: Replace an existing customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Full customer object to replace the existing one
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request, possibly due to missing fields
        '404':
          description: Customer not found

    patch:
      summary: Partially update an existing customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Partial customer object to update the existing one
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request, possibly due to invalid fields
        '404':
          description: Customer not found

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
      required:
        - id
        - name
        - age
